version: 2

models:
  - name: test
    description: This table contains clickstream events from the marketing website

    columns:
      - name: event_id
        description: This is a unique identifier for the event

      - name: user-id
        quote: true
        description: The user who performed the event
